package com.avob.openadr.server.common.vtn.models.demandresponseevent;

import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;


import com.avob.openadr.server.common.vtn.models.ItemBase;
import com.avob.openadr.server.common.vtn.models.Target;

@Entity
@Table(name = "demandresponseeventsignal")
public class DemandResponseEventSignal {
	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	/**
	 * oadrDistributeEvent 에 그대로 나가는 signalID. 자유 문자열이다.
	 * 예를 들어 연계 VTN 규격은 기본 지령을 SIG_01, 특정 참여자는 SIG_01-C:{참여자ID},
	 * 특정 자원은 SIG_01-R:{자원ID} 로 구분한다. 비어 있으면 예전처럼 이벤트 안의 순번(0, 1, 2 ...)을 쓴다.
	 * 운영 DB(ddl-auto 가 update 가 아닌 곳)에는 이 컬럼을 직접 추가해야 한다:
	 * ALTER TABLE demandresponseeventsignal ADD COLUMN signal_id varchar(255);
	 */
	@Column(name = "signal_id")
	private String signalId;

	@NotNull
	private DemandResponseEventSignalNameEnum signalName;

	@NotNull
	private DemandResponseEventSignalTypeEnum signalType;

	@ElementCollection(fetch = FetchType.EAGER)
	private List<DemandResponseEventSignalInterval> intervals;

	private Float currentValue;

	private ItemBase itemBase;

	// @LazyCollection(FALSE) 는 하이버네이트 6 에서 deprecated, 7 에서 제거된다.
	// @ElementCollection 의 기본이 LAZY 라 EAGER 를 직접 지정해 같은 동작을 유지한다
	@ElementCollection(fetch = FetchType.EAGER)
	private List<Target> targets;

	/**
	 * Related event
	 */
	@ManyToOne
	@JoinColumn(name = "demandresponseevent_id")
	private DemandResponseEvent event;

	public String getSignalId() {
		return signalId;
	}

	public void setSignalId(String signalId) {
		this.signalId = signalId;
	}

	/**
	 * oadrDistributeEvent 에 실을 signalID. 지정한 값이 없거나 공백뿐이면 이벤트 안의 순번을 쓴다.
	 * DTO 매퍼가 공백을 null 로 바꿔 저장하지만, 다른 경로로 들어온 값도 같은 규칙을 따르게 여기서 한 번 더 본다.
	 * 2.0a, 2.0b VTN 이 같이 쓴다
	 *
	 * @param index 이벤트 안에서 이 시그널의 순서(0 부터)
	 */
	public String signalIdOrIndex(int index) {
		return (signalId == null || signalId.isBlank()) ? String.valueOf(index) : signalId;
	}

	public DemandResponseEventSignalNameEnum getSignalName() {
		return signalName;
	}

	public void setSignalName(DemandResponseEventSignalNameEnum signalName) {
		this.signalName = signalName;
	}

	public DemandResponseEventSignalTypeEnum getSignalType() {
		return signalType;
	}

	public void setSignalType(DemandResponseEventSignalTypeEnum signalType) {
		this.signalType = signalType;
	}

	public List<DemandResponseEventSignalInterval> getIntervals() {
		return intervals;
	}

	public void setIntervals(List<DemandResponseEventSignalInterval> intervals) {
		this.intervals = intervals;
	}

	public Float getCurrentValue() {
		return currentValue;
	}

	public void setCurrentValue(Float currentValue) {
		this.currentValue = currentValue;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DemandResponseEvent getEvent() {
		return event;
	}

	public void setEvent(DemandResponseEvent event) {
		this.event = event;
	}

	public ItemBase getItemBase() {
		return itemBase;
	}

	public void setItemBase(ItemBase itemBase) {
		this.itemBase = itemBase;
	}

	public List<Target> getTargets() {
		return targets;
	}

	public void setTargets(List<Target> targets) {
		this.targets = targets;
	}

}
