package com.avob.openadr.server.common.vtn.models.demandresponseevent;

import java.util.List;
import java.util.Set;

import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;


import com.avob.openadr.server.common.vtn.models.Target;
import com.avob.openadr.server.common.vtn.models.vendemandresponseevent.VenDemandResponseEvent;

/**
 * An entity of DemandResponseEvent
 * 
 * @author bertrand
 *
 */
@Entity
@Table(name = "demandresponseevent")
public class DemandResponseEvent {

	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@NotNull
	private Long createdTimestamp = System.currentTimeMillis();

	private Long lastUpdateTimestamp;

	private boolean published = false;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	private List<VenDemandResponseEvent> venDemandResponseEvent;

	private DemandResponseEventDescriptor descriptor;

	private DemandResponseEventActivePeriod activePeriod;

	@OneToOne(fetch = FetchType.EAGER)
	private DemandResponseEventBaseline baseline;

	// 입력 순서(id)를 지킨다. @OrderBy 가 있으면 하이버네이트가 Set 을 LinkedHashSet 으로 채운다.
	// 조회 DTO 와 화면의 시그널 순서가 등록한 순서와 같아진다
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "event")
	@OrderBy("id ASC")
	private Set<DemandResponseEventSignal> signals;

	// @LazyCollection(FALSE) 는 하이버네이트 6 에서 deprecated, 7 에서 제거된다.
	// @ElementCollection 의 기본이 LAZY 라 EAGER 를 직접 지정해 같은 동작을 유지한다
	@ElementCollection(fetch = FetchType.EAGER)
	private List<Target> targets;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCreatedTimestamp() {
		return createdTimestamp;
	}

	public void setCreatedTimestamp(Long createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	public Long getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Long lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public DemandResponseEventDescriptor getDescriptor() {
		if (descriptor == null) {
			descriptor = new DemandResponseEventDescriptor();
		}
		return descriptor;
	}

	public void setDescriptor(DemandResponseEventDescriptor descriptor) {
		this.descriptor = descriptor;
	}

	public DemandResponseEventActivePeriod getActivePeriod() {
		if (activePeriod == null) {
			activePeriod = new DemandResponseEventActivePeriod();
		}
		return activePeriod;
	}

	public void setActivePeriod(DemandResponseEventActivePeriod activePeriod) {
		this.activePeriod = activePeriod;
	}

	public Set<DemandResponseEventSignal> getSignals() {
		return signals;
	}

	public void setSignals(Set<DemandResponseEventSignal> signals) {
		this.signals = signals;
	}

	public List<Target> getTargets() {
		return targets;
	}

	public void setTargets(List<Target> targets) {
		this.targets = targets;
	}

	public boolean isPublished() {
		return published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	public DemandResponseEventBaseline getBaseline() {
		return baseline;
	}

	public void setBaseline(DemandResponseEventBaseline baseline) {
		this.baseline = baseline;
	}

}
