package com.avob.openadr.server.oadr20b.vtn.models.venreport.capability;

import java.util.List;

import jakarta.persistence.ElementCollection;
import jakarta.persistence.FetchType;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;


import com.avob.openadr.model.oadr20b.ei.ReadingTypeEnumeratedType;
import com.avob.openadr.model.oadr20b.ei.ReportEnumeratedType;
import com.avob.openadr.server.common.vtn.models.ItemBase;
import com.avob.openadr.server.common.vtn.models.Target;

/**
 * @author bzanni
 *
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class ReportCapabilityDescription {

	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long id;

	private String rid;

	@Enumerated(EnumType.STRING)
	private ReportEnumeratedType reportType;

	@Enumerated(EnumType.STRING)
	private ReadingTypeEnumeratedType readingType;

	private SamplingRate samplingRate;

	private ItemBase itemBase;

	// @LazyCollection(FALSE) 는 하이버네이트 6 에서 deprecated, 7 에서 제거된다.
	// @ElementCollection 의 기본이 LAZY 라 EAGER 를 직접 지정해 같은 동작을 유지한다
	@ElementCollection(fetch = FetchType.EAGER)
	private List<Target> eiDatasource;

	// @LazyCollection(FALSE) 는 하이버네이트 6 에서 deprecated, 7 에서 제거된다.
	// @ElementCollection 의 기본이 LAZY 라 EAGER 를 직접 지정해 같은 동작을 유지한다
	@ElementCollection(fetch = FetchType.EAGER)
	private List<Target> eiSubject;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRid() {
		return rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	public ReportEnumeratedType getReportType() {
		return reportType;
	}

	public void setReportType(ReportEnumeratedType reportType) {
		this.reportType = reportType;
	}

	public ReadingTypeEnumeratedType getReadingType() {
		return readingType;
	}

	public void setReadingType(ReadingTypeEnumeratedType readingType) {
		this.readingType = readingType;
	}

	public ItemBase getItemBase() {
		return itemBase;
	}

	public void setItemBase(ItemBase itemBase) {
		this.itemBase = itemBase;
	}

	public List<Target> getEiDatasource() {
		return eiDatasource;
	}

	public void setEiDatasource(List<Target> eiDatasource) {
		this.eiDatasource = eiDatasource;
	}

	public List<Target> getEiSubject() {
		return eiSubject;
	}

	public void setEiSubject(List<Target> eiSubject) {
		this.eiSubject = eiSubject;
	}

	public SamplingRate getSamplingRate() {
		return samplingRate;
	}

	public void setSamplingRate(SamplingRate samplingRate) {
		this.samplingRate = samplingRate;
	}
}
